[project]
id      = "gl"
version = "0.1.0"
module  = "gl.mach"
target  = "native"
src     = "src"
dep     = "dep"
out     = "out/{target}/bin/{name}{ext}"
obj     = "out/{target}/obj"

[target.linux]
isa = "x86_64"
os  = "linux"
abi = "sysv64"

[target.windows]
isa = "x86_64"
os  = "windows"
abi = "win64"
ext = ".exe"

[target.darwin]
isa = "x86_64"
os  = "darwin"
abi = "sysv64"

[lib.gl]
entry = "gl.mach"

[deps.mach-std]
git = "https://github.com/octalide/mach-std"
ref = "v0.5.0"
