[project]
id = "gl"
version = "0.3.0"
src = "src"
out = "out/{target.name}/{profile.name}"

[target.linux-x86_64]
isa = "x86_64"
os  = "linux"
abi = "sysv64"

[target.windows]
isa = "x86_64"
os  = "windows"
abi = "win64"

[target.darwin]
isa = "x86_64"
os  = "darwin"
abi = "sysv64"

[profile.debug]
opt = 0
debug = true
simd = "scalarize"

[profile.release]
opt = 2
debug = false
simd = "scalarize"

[artifact.gl]
kind = "static"
entry = "gl.mach"
out = "lib/gl"
targets = ["*"]
link = []
need = []

[dep.mach-std]
git = "https://github.com/briar-systems/mach-std"
ref = "branch/main"
