[project]
id      = "demo"
version = "0.1.0"
target  = "native"
src     = "src"
dep     = "dep"
out     = "out/{target}/bin/{name}{ext}"
obj     = "out/{target}/obj"

[target.linux]
isa = "x86_64"
os  = "linux"
abi = "sysv64"

[bin.demo]
entry = "main.mach"

[deps.mach-gl]
path = "../.."

[deps.mach-glfw]
git = "https://github.com/briar-systems/mach-glfw"
ref = "branch/main"

[deps.mach-std]
git = "https://github.com/briar-systems/mach-std"
ref = "branch/main"
